#!/usr/bin/perl 
use 5.014 ; use strict ; use warnings  ;
use feature qw [ say ] ;
#use Time::HiRes qw[gettimeofday tv_interval] ; my $time_start = [ gettimeofday ] ; 
use Term::ANSIColor qw [ :constants color ] ; $Term::ANSIColor::AUTORESET = 1 ; 
use File::Spec::Functions qw[ catfile splitdir ] ; 
use Getopt::Std ; getopts '.cdvy' , \my%o ; 
my $I = catfile '' , '' ; # OS毎に異なる可能性のある、ファイルパスの区切り文字を取得。 
my $start_dir = $ARGV [0] // "." ;
my $root = ::dirtree -> new ( undef ) ;
chdir $start_dir or die ; 
#say map "[$_]" , & get_dirs ( $start_dir ) ;
our $m = 0 ;
my $depth = 0 ;
$root -> rec_dir ( "." , $depth ) ; 
exit 0 ;

sub get_dirs () { 
  opendir my $dh , '.' or warn $_[0] ; 
  my @dirs0 = readdir $dh ;
  my @dirs = grep { ! /\A\.{1,2}\Z/ && -d $_ } @dirs0 ; #readdir $dh ; # 隠しファイルの処理も加えたい <-- -d に限定している
  print FAINT map "[$_]" , @dirs ;
  chdir $dh ;
  closedir $dh ; 
  return @dirs ; 
}

END{ print RESET "" } ;

package dirtree ;
use Term::ANSIColor qw [ :constants color ] ; $Term::ANSIColor::AUTORESET = 1 ; 

sub new { my %keep = ( dirname => $_[1] // undef , children => [] ) ;	bless \%keep ; } 

sub rec_dir ( $$ ) { #  第1引数に子ディレクトリの名前
	if  ( $m < $_[2]) { $m = $_[2] ; print YELLOW "$m "}
	opendir my $dh , '.' ;
	print YELLOW $_[1] ;
	chdir $_[1] or do { warn FAINT RED $_ ; return }  ;
	my $ch = new ( $_[1] ) ; 
	push @{ $_[0] -> { children } } , $ch ;
	$ch -> rec_dir ( $_  , $_[2] + 1 ) for ::get_dirs ; # $_[1] ) ;
	chdir $dh ; 
}

